// This file was automatically generated by ipc-messages.mjs. Do not modify this file manually!

export const LogType = {
  info: 0,
  error: 1,
  warn: 2,
  debug: 3,
};

export const IM = {
  rpc_update: 0,
  rpc_clear: 1,
  save_config: 2,
  shell_open: 3,
  fullscreen: 4,
  update_meta: 5,
  revert_meta: 6,
  reload_config: 7,
  browse_file: 8,
  mousedown: 9,
  mouseup: 10,
  mousemove: 11,
  mousewheel: 12,
  pointer: 13,
  open_devtools: 14,
  log: 15,
  relaunch_webview: 16,
  close_window: 17,
  reload_window: 18,
  seek_game: 19,
  account_list: 20,
  account_password: 21,
  account_set: 22,
  account_remove: 23,
  account_set_password: 24,
  account_regen: 25,
  update_menu: 26,
  get_ping_region: 27,
};
