/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Userscript {
  /**
   * Name of the userscript
   */
  name?: string;
  /**
   * Namespace to associate the userscript with
   */
  author: string;
  /**
   * Small description of the userscript
   */
  description?: string;
  /**
   * Version of the userscript
   */
  version?: string | number;
  /**
   * Locations the script will run at
   */
  locations?: [] | ["all" | "game" | "social" | "editor"];
  /**
   * APIs to configure/provide to the script
   */
  features?: {
    /**
     * Regex pattern to match against a full URL to determine if the URL will be blocked.
     */
    block?: string;
    command_line?: string[];
    gui?: {
      /**
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` "^.*$".
       */
      [k: string]: {
        /**
         * Key will be the category title.
         *
         * This interface was referenced by `undefined`'s JSON-Schema definition
         * via the `patternProperty` "^.*$".
         */
        [k: string]: {
          /**
           * Type of control to create
           */
          type: string;
          /**
           * Config path to save value to.
           */
          walk?: string;
          /**
           * Reference to exported function. Ie if change = 'changeGUI', exports.changeGUI must be set to receive the event
           */
          change?: string;
          [k: string]: unknown;
        };
      };
    };
    /**
     * A JSON-serializable config. Changes will be reflected in metadata.config.
     */
    config?: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
